Todo
degisew/React-To-Do-List-App pull request #1
Opened 2022-09-24 06:07 UTC by degisew

### ToDo List App
**In this PR I implemented the following features:**

-  Setup project with CRA
-  Using Components
-  Using Props and state
-  Using Hooks with function-based components
-  Using React Router 
-  Using React Icons

2022-09-24 21:00 UTC, Tommymarvel requested changes
Hi @degisew   

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>

## Highlights
 - [x] Correct GitH  flow practice :heavy_check_mark:
 - [X] Linters are passing :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 21:00 UTC, Tommymarvel commented on src/classBased/components/TodoContainer.js
> +  // }
Kindly remove the dead code, to make your code clean :+1:

2022-09-24 21:00 UTC, Tommymarvel commented on src/functionBased/pages/About.js
> +  //   const { url, path } = useRouteMatch();
Kindly remove the dead code.

2022-09-29 15:51 UTC, saikatgpae commented
> ### ToDo List App
> **In this PR I implemented the following features:**
> 
> * Setup project with CRA
> * Using Components
> * Using Props and state
> * Using Hooks with function-based components
> * Using React Router
> * Using React Icons

APPROVED!!!! 🎉 🎉 🎉 🎉 🎉 🎉
Hey @degisew  😊 😃
Great Job 😄 👏 You've done it. Your project is complete!

Highlights 🚀 ✔️ ✔️
The repo looks professional ✔️
Git/GitHub flow best practices have been followed ✔️
You have a descriptive PR ✔️
Professional README 💯
Meaningful commit messages ✔️
No linter errors ✔️
The app works as expected ✔️
There is nothing else to say other than... it's time to merge it 👍🏻 ✅

Congratulations!!! 🎉 🥳 👏 🙌 🎊
Cheers and Happy coding!👏👏👏

2022-10-01 10:01 UTC, merged